/// Flutter icons SocialMediaIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SocialMediaIcons
///      fonts:
///       - asset: fonts/SocialMediaIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SocialMediaIcons {
  SocialMediaIcons._();

  static const _kFontFam = 'SocialMediaIcons';
  static const String? _kFontPkg = null;

  static const IconData apple =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spotify =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lastfm =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strava =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
